name: calorie_track
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  bloc: ^8.1.4
  fl_chart: ^0.69.0
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite: ^2.4.1
  logger: ^2.5.0
  http: ^1.2.2
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  shared_preferences: ^2.3.4
  cloud_firestore: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: "ic_launcher"
  ios: false
  remove_alpha_ios: true